export const feedActions = {
  IS_LOADING: 'IS_LOADING',
  SHOW_ERROR: 'SHOW_ERROR',
  UPDATE_FEEDS: 'UPDATE_FEEDS',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  SHOW_USER_INFO_ERROR: 'SHOW_USER_INFO_ERROR',
  FETCHED_BLACKLIST: 'FETCHED_BLACKLIST',
  FETCHED_BLACKLIST_ERROR: 'FETCHED_BLACKLIST_ERROR',
  STOP_FETCHING_FEEDS: 'STOP_FETCHING_FEEDS',
  POST_IS_FINISHED: 'POST_IS_FINISHED',
  IS_FETCHING_FEED: 'IS_FETCHING_FEED',
  FAILED_FETCHING_FEEDS: 'FAILED_FETCHING_FEEDS',
};
